version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=Administrador
      - DB_PASSWORD=Panama26
      - DB_NAME=sistema_apuestas
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=Administrador
      - MYSQL_PASSWORD=Panama26
      - MYSQL_DATABASE=sistema_apuestas
    ports:
      - "3307:3306" # Expuesto al exterior en el puerto 3307 por seguridad (Workbench/DBeaver)
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql # Auto-inicializa las tablas
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uAdministrador", "-pPanama26"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" # Abierto para la red Wi-Fi local
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  db_data:
